### ISSUE TITLE
Backlog for Writers WG

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#117]
2023 Meeting Summary - https://docs.google.com/spreadsheets/d/1JhXslq49PmHg2zrjPXTYmMYIL3UMdVIQPKbmLjAC64E/edit?usp=sharing

2024 Meeting Summary - https://docs.google.com/spreadsheets/d/1S1M-IlMnI4WPL2c_ojOeIExvWU-bkzfamirE5_Ls9-4/edit?usp=sharing

**Comment by VanCardui** [comment]
All added to GitBook - am closing the Issue
