### ISSUE TITLE
Archival workflow design

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#12]
Design and document workflow for archiving and updating content on SingularityNET GitBooks.

**Comment by stephen-rowan** [comment]
Practical part of meeting will demonstrate how workflow might work

**Comment by VanCardui** [comment]
So far, after discussions, the workflow is

1. Within a week of the date of a meeting (ideally, sooner) the WG facilitator collects whatever is the agreed documentation from the meeting, and posts it in Discord "Meeting summary" channel (complete with date and title of meeting, and formatted). NB Different WGs will collect different things; but they should aim to be consistent in having the same things each meeting.
2. An Archives team member cut-and-pastes the material to the Archives GitBook
3. (TBC) The Archives team will develop a tags taxonomy, and tag posts appropriately. This will form the start of a finding-aid process. Taxonomy to be develped with community input?
4. If the Archive team member is aware of any additional material related to the meeting (e.g. a video or slide deck that the facilitator forgot to post), they should add it - but they should not actively go searching for more material to add.
5. The Archive team member replies in the Discord meeting summary channel with a link to where the material is on GitBook, for confirmation; and also states anything they added.
6. WG facilitator can then raise any corrections needed by replying in Discord. Any Archives team member can make the correction, and should reply in Discord to say it's done.

**Comment by stephen-rowan** [comment]
- Meeting notes changed often - Tevo
- We need to integrate this into our archival workflow - Vani
- Becomes like Spam if too much information or notes added - Tevo
- If a person facilitates more than one workgroup - connections can be made between WGs - A month from the day of the meeting do updates - Vani

**Comment by stephen-rowan** [comment]
Meeting 4 - 5th July 2023

- Meeting summary channel is only for meetings not discussion - Vanessa
- How we close issues - Archive issue for each month - Vanessa
- Miro is just going focus on Archive WG transcriptions - Stephen
- Look for new Archive resource to assist Vanessa 
- Write off meetings not submitting summaries - Vanessa
- Settle for a partial Archive - Vanessa
- Less participation ? - Tevo

**Comment by VanCardui** [comment]
Note that Andre's interface will send a copy of a meeting summary to the Discord meeting summary channel.

And adding to GitBook will be automatic - won't need anyone to actually archive it separately

**Comment by VanCardui** [comment]
Current workflow as of Sept 2023 https://docs.google.com/document/d/1OshEmaikeOta7STfQRm51An2meJdVJMJLOOBQQ9iJfI/edit?usp=sharing

**Comment by stephen-rowan** [comment]
-  [ ] Action Item - @VanCardui to tidy up workflow document and close issue

**Comment by VanCardui** [comment]
Final version of workflow is here https://docs.google.com/document/d/1OshEmaikeOta7STfQRm51An2meJdVJMJLOOBQQ9iJfI/edit?usp=sharing 

Issue closed
