### ISSUE TITLE
Archive GitBook - June 2023

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#26]
## Month
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023
- [x] Month Issue embedded in GitBook

## Notes

```
To insert detail use /detail slash command
``` 

## Week Numbers
- https://www.epochconverter.com/weeks/2023

### Week 22 - 29th May to 4th June 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-22
### Week 23 - 5th June to 11th June 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-23
### Week 24 - 12th June to 18th June 
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-24
### Week 25 - 19th June to 25th June
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-25
### Week 26 - 26th June to 2nd July
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-26

**Comment by stephen-rowan** [comment]
## Video Workgroup

Rojo and the Video Workgroup are using the Summon platform for decision making.
- https://summonplatform.io/
Some though and observation needs to be given to document and archive this experiment

**Comment by stephen-rowan** [comment]
### Week 23 - 5th June to 11th June 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-23

### Monday 5th June 2023

- [ ] Education Guild
- [ ] Broadcast Ideation

### Tuesday 6th June 2023

- [x] Governance Work group
- [x] Ambassador Work group
- [x] Ambassador Town Hall
- [x] Process Guild

### Wednesday 7th June 2023

- [x] Process Modelling Work group
- [x] Archive Workgroup
- [x] Incubation Workshop
- [x] Strategy Guild

### Thursday 8th June 2023

- [ ] Onboarding Workgroup
- [x] AI Sandbox
- [x] Treasury Guild
- [ ] DeepFunding Town Hall


### Friday 9th June 2023

- [x] Marketing Guild
- [ ] Video Workgroup
- [x] Writers Workgroup

**Comment by VanCardui** [comment]
Note: If a meeting isn't archived because it doesn't happen, then add a note after it to say so - 
Stephen to look at Summon platform and how Rojo's video group is using it.

ACTION: add the link-back to the GitHub month issue at the top of the page for each week in the GitBook.

**Comment by stephen-rowan** [comment]
## Screen shots of the Summon Platform used by Video Workgroup & Rojp

<details><summary>Entry Screen</summary>
<p>

![Image](https://github.com/SingularityNET-Archive/SingularityNET-Archive/assets/25156451/ed562f3c-216c-4e14-8582-57af1e906ced)

</p>
</details> 

<details><summary>Landing Page</summary>
<p>

Landing Page of DAO 

![Image](https://github.com/SingularityNET-Archive/SingularityNET-Archive/assets/25156451/177e9449-263b-4ec6-8fa7-6a7e88784df2)

</p>
</details> 

<details><summary>Snapshot Voting</summary>
<p>

Snapshot Voting Section

![Image](https://github.com/SingularityNET-Archive/SingularityNET-Archive/assets/25156451/01a1f59b-e5c7-4ada-85f8-6cfd55867adb)


</p>
</details>

**Comment by stephen-rowan** [comment]
### Week 24 - 12th June to 18th June 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-23

<details><summary>Details</summary>
<p>

### Monday 12th June 2023

- [x] Education Guild
- [ ] Broadcast Ideation

### Tuesday 13th June 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall
- [ ] Process Guild

### Wednesday 14th June 2023

- [ ] Process Modelling Work group
- [ ] Archive Workgroup
- [ ] Incubation Workshop
- [ ] Strategy Guild

### Thursday 15th June 2023

- [ ] Onboarding Workgroup
- [ ] AI Sandbox
- [ ] Treasury Guild
- [ ] DeepFunding Town Hall


### Friday 16th June 2023

- [ ] Marketing Guild
- [ ] Video Workgroup
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
Week 25 - 19th June to 25th June 2023

### Monday 19th June 2023

- [ ] Education Guild
- [ ] Broadcast Ideation

### Tuesday 20th June 2023

- [x] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall
- [x] Process Guild

### Wednesday 21st June 2023

- [ ] Archive Workgroup
- [x] Process Modelling Workgroup
- [ ] Incubation Workshop
- [ ] Strategy Guild

### Thursday 22nd June 2023

- [ ] Onboarding Workgroup - not this week
- [ ] AI Sandbox
- [x] Treasury Guild
- [ ] DeepFunding Town Hall


### Friday 23rd June 2023

- [ ] Marketing Guild
- [x] Video Workgroup
- [ ] Writers Workgroup

**Comment by VanCardui** [comment]
### Week 26 - 26th June to 2nd July 2023
https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/june-2023/week-26

<details><summary>Details</summary>

### Monday 26th June 2023

- [ ] Education Guild
- [ ] Broadcast Ideation

### Tuesday 27th June 2023

- [ ] Governance Work group - not this week
- [ ] Ambassador Work group
- [x] Ambassador Town Hall
- [x] Process Guild

### Wednesday 28thJune 2023

- [ ] Archive Workgroup -not this week
- [x] Process Modelling Workgroup
- [x] Incubation Workshop
- [x] Strategy Guild

### Thursday 29th June 2023

- [x] Onboarding Workgroup
- [ ] AI Sandbox
- [x] Treasury Guild
- [x] DeepFunding Town Hall


### Friday 30th June 2023

- [ ] Marketing Guild
- [x] Video Workgroup
- [ ] Writers Workgroup

**Comment by stephen-rowan** [comment]
Meeting 4 - 5th July 2023

- Keep open a week after end of month to do chasing - Vanessa
- Do not ping Tevo when Archive summaries added

**Comment by stephen-rowan** [comment]
A few June 2023 meetings not archived
Ambassadors TH not being archived regularly
read.ai transcript can provide key words - Vani
Duplication of meeting summaries ? - Tevo
First half is update of WG status - Peter
Overview of what happened and overview of next actions - Peter
More important to capture second half ? - Peter
Importance realized after the event - Vani
Lets check read.ai - Peter 
Ambassadors TH Slides in public folder - Peter 
Threshold for closing Monthly Archive ? - Stephen
Chase once - Tevo
Approach WG lead and post in WG channel to chase - Vanessa

- [ ] Give access to read.ai for Vani - ambassador account needed - Tevo
