### ISSUE TITLE
Training GitBook Lens LLM

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#27]
Training GitBook Lens LLM

- GitBook Lens training - https://github.com/orgs/SingularityNET-Archive/discussions/6

Important we pay attention to LLM training and build better access tools - MeshJS.ai make data structures compatible - use case Discord Q&A - compare notes on LLM - Felix

**Comment by stephen-rowan** [comment]
Not just a search function. To move to an archive we need organization. Archival finding aids can support determining community meaning of corpus. LLMs could be used effectively as finding aids. Could act as a demonstration - Vanessa

Will keep this in mind when working on the Javascript - Andre

Important we pay attention to LLM training and build better access tools - MeshJS.ai make data structures compatible - use case Discord Q&A - compare notes on LLM - Felix

**Comment by VanCardui** [comment]
Related to issue #29
