### ISSUE TITLE
Tool development - June 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#33]
Created [archive-oracle](https://github.com/SingularityNET-Archive/archive-oracle) Repo to experiment with Langchain and Huggingface in JavaScript environment.

- https://github.com/SingularityNET-Archive/archive-oracle/issues/1
- https://github.com/SingularityNET-Archive/archive-oracle/issues/2

**Comment by Andre-Diamond** [comment]
Next steps - Install Langchain and Huggingface and do simple API call

**Comment by stephen-rowan** [comment]
- Created repo - installed framework - install Langchain and huggingface. Setup Superbase database (may have vector database). - Andre
- At some point document the development process and functionality - Andre

**Comment by stephen-rowan** [comment]
## Meeting 3 - 21st June 2023 Update
 - https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/37

- Arrange meeting with Jingles at Mesh.ai to discuss possible - Felix / @Andre-Diamond

**Comment by stephen-rowan** [comment]
Meeting 4 - 5th July 2023

Meeting with Jingles gave guidance - use of openai api - will be a minimal cost - start building - Andre
Charge against Archive WG budget as query costs - will do minimal queries to assess likely cost - Andre

- Need to break up meeting notes into topics - isolate decision items in meeting summaries for funnel to database - create template for meeting summaries - create page on tool being building and login with Discord - Discord role transfer to meeting record - Andre
