### ISSUE TITLE
Archive GitBook Backlog part 1

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#36]
This issue tracks work on the Archive GitBook Backlog in May 2022

### May 2022

- Ambassador Program kick-off Townhall | 10th of May 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-19#ambassador-program-kick-off-townhall

- Ambassador Program Town Hall Meeting 2 | 17th of May 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-20#ambassador-program-town-hall-meeting-2

- Ambassador Workgroup meeting | Community Podcast - Friday, 20th May 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-20#ambassador-workgroup-meeting-or-community-podcast

- Ambassador Workgroup meeting | Structure/Incubation workgroup - Monday, 23rd May 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-21#ambassador-workgroup-meeting-or-structure-incubation-workgroup

- Ambassador Town Hall meeting 3 | May 24th 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-21#ambassador-town-hall-meeting-3

- Ambassador Workgroup meeting | Community Podcast May 27th 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/may-2022/week-21#ambassador-workgroup-meeting-or-community-podcast

- Catalyst Swarm - SingularityNet & Deepfund
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/june-2022/week-22#catalyst-swarm-singularitynet-and-deepfund

- Ambassador Town Hall meeting 4 | May 31 2022
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2022/june-2022/week-22#ambassador-town-hall-meeting-4-or-may-31-2022

**Comment by stephen-rowan** [comment]
Meeting 4 - 5th July 2023

- [ ] Break this issue into months for fund requests - Stephen 
- How much to archive a whole month ? - Stephen
- More work because you have to search for sources - Vanessa
- Flat rate for archiving a month ? - Vanessa

**Comment by stephen-rowan** [comment]
Possibly can contribute - Vanessa
We could workgroup a backlog archive - Tevo
Aysnc discuss with Tevo - Stephen 
From next Thursday 4th August 2023 ?
Related to How To videos - Vanessa

**Comment by stephen-rowan** [comment]
Main blocker - whether to archive Miro boards from past - Vani
- [ ] Agree not to archive past Miro boards - All
- [ ] Archive only links to Miro Boards - All

How to archive text records from the past ? - Stephen
- [ ] Look into use of otter.ai to process historical meetings - Stephen

**Comment by stephen-rowan** [comment]
- [ ] [Action Item] - Approach access to read.ai from Tevo - Andre

**Comment by stephen-rowan** [comment]
- [ ] [Action Item] - Add links to Miro Board

**Comment by stephen-rowan** [comment]
Use of read.ai to archive historical meetings discussed.

Start capturing past videos in read.ai
SNet Ambassadors and SNet YouTube channels
Agreed mostly to use for transcripts. Attach transcript to GitBook Archive.

**Comment by VanCardui** [comment]
Closing this issue with work done so far - scoping, planning, and completion of May 2022 backlog - and submitting fund request.
