### ISSUE TITLE
Quarter 2 2023 report for Archives WG

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#39]

**Comment by VanCardui** [comment]
Draft version here https://docs.google.com/document/d/1J7kgYXPTVaK1qlS9NtFZe-c6aFTtiWRVUosgmV9j4yM/edit?usp=sharing

Peter is collecting them, so we should send it to him when agreed

**Comment by VanCardui** [comment]
4th July 2023: text of report agreed. Sent to Peter.

**Comment by stephen-rowan** [comment]
Meeting 4 - 5th July 2023

- [ ] Peter to review and sign off

**Comment by stephen-rowan** [comment]
Should a quarterly report refer to plans for next quarter ? - Vani
Makes sense to have future activities - Peter
