### ISSUE TITLE
Tool development - July 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#43]
- https://github.com/SingularityNET-Archive/archive-oracle/issues/3
- Created openai account and experimenting with example repo https://github.com/Andre-Diamond/doc-search

**Comment by Andre-Diamond** [comment]
Next steps is to build database tables and create sample markdown files to create and test API calls and embeddings

**Comment by stephen-rowan** [comment]
Complements tool development and guidance notes -Andre
Work to commence shortly.
Initial setup will take a few hours - Andre
