### ISSUE TITLE
Archive GitBook - July 2023

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#45]
## Month
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023
- [x] Month Issue embedded in GitBook

## Notes

```
To insert detail use /detail slash command
``` 

## Week Numbers
- https://www.epochconverter.com/weeks/2023

### Week 27 - 3rd July to 9th July 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-27
### Week 28 - 10th July to 16th July 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-28
### Week 29 - 17th July to 23rd July 
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-29
### Week 30 - 24th July to 30th July
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-30

**Comment by VanCardui** [comment]
### Week 27 - 3rd July to 9th July 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-27

<details><summary>Details</summary>
<p>

### Monday 3rd July 2023

- [ ] Education Guild - no meeting this week
- [ ] Broadcast Ideation - no meeting this week

### Tuesday 4th July 2023

- [ ] Governance Work group - no meeting this week
- [ ] Ambassador Work group -no summary given
- [ ] Ambassador Town Hall - no summary given
- [x] Process Guild

### Wednesday 5th July 2023

- [ ] Archives Workgroup - no meeting this week
- [x] Process Modelling Workgroup
- [ ] Incubation Workgroup - no summary given
- [ ] Strategy Guild - no summary given

### Thursday 6th July 2023

- [ ] Onboarding Workgroup - no meeting this week
- [x] Treasury Guild
- [ ] AI Sandbox - no summary given
- [ ] DeepFunding Town Hall - no summary given


### Friday 7th July 2023

- [ ] Video Workgroup - no summary given
- [ ] Writers Workgroup - no summary given


</p>
</details>

**Comment by VanCardui** [comment]
### Week 28 - 10th July to 16th July 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-28

<details><summary>Details</summary>
<p>

### Monday 10th July 2023

- [ ] Education Guild - no meeting this week
- [ ] Broadcast Ideation - no meeting this week

### Tuesday 11th July 2023

- [ ] Governance Work group - no meeting this week
- [ ] Ambassador Work group -no summary given
- [ ] Ambassador Town Hall - no summary given
- [ ] Process Guild

### Wednesday 12th July 2023

- [ ] Archives Workgroup - no meeting this week
- [x] Dework PBL Workgroup
- [x] Process Modelling Workgroup
- [x] Incubation Workgroup 
- [ ] Strategy Guild - no summary given

### Thursday 13th July 2023

- [x] Onboarding Workgroup
- [ ] Treasury Guild - no summary given
- [ ] AI Sandbox - no summary given
- [ ] DeepFunding Town Hall - no summary given


### Friday 14th July 2023

- [ ] Video Workgroup - no summary given
- [ ] Writers Workgroup - no summary given


</p>
</details>

**Comment by VanCardui** [comment]
### Week 29 - 17th July to 23rd July 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/july-2023/week-29

<details><summary>Details</summary>
<p>

### Monday 17th July 2023

- [x] Education Guild
- [ ] Broadcast Ideation - no meeting this week

### Tuesday 18th July 2023

- [x] Governance Work group
- [ ] Ambassador Work group -no summary given
- [ ] Ambassador Town Hall - no summary given
- [x] Process Guild

### Wednesday 19th July 2023

- [ ] Archives Workgroup - no meeting this week
- [x] Dework PBL Workgroup
- [x] Process Modelling Workgroup
- [ ] Incubation Workgroup - no summary given
- [x] Strategy Guild 

### Thursday 20th July 2023

- [ ] Onboarding Workgroup - no meeting this week
- [x] Treasury Guild
- [ ] AI Sandbox - no summary given
- [ ] DeepFunding Town Hall - no summary given


### Friday 21st July 2023

- [ ] Video Workgroup - no summary given
- [ ] Writers Workgroup - no summary given


</p>
</details>

**Comment by VanCardui** [comment]
week 30
