### ISSUE TITLE
Quarter 3 2023 report for Archives WG

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#46]
Start making notes here to prepare for report
- Ongoing archiving
- Tool Development
- Backlog

**Comment by stephen-rowan** [comment]
6th September

Anything to share about meeting summary interface

**Comment by VanCardui** [comment]
## 20th Sept

Draft report is here https://docs.google.com/document/d/1OshEmaikeOta7STfQRm51An2meJdVJMJLOOBQQ9iJfI/edit?usp=sharing 

Went through it during meeting - comments added - Vanessa to tidy it up, submit it, and close the issue by 27th Sept 2023

**Comment by VanCardui** [comment]
Final version here https://docs.google.com/document/d/1bzZNTs9mwCXJnti92i3cqhjqr0ULf3tz15RA2ydT3G0/edit?usp=sharing

has been shared in Discord Archives channel, and in Ambassador General channel, tagging Peter.

This Issue had no cost attached. The Q2 monthly report was costed at $50, so I did the same here, and closed this Issue.
