### ISSUE TITLE
Archive Gitbook - August 2023

### ISSUE THREAD

**Issue by VanCardui** [SingularityNET-Archive/SingularityNET-Archive#48]
## Month
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023
- [x] Month Issue embedded in GitBook

## Notes

```
To insert detail use /detail slash command
``` 

## Week Numbers
- https://www.epochconverter.com/weeks/2023

### Week 31 - 31st July to 6th August 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-31
### Week 32 - 7th August to 13th August 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-32
### Week 33 - 14th August to 20th August 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-33
### Week 34 - 21st August to 27th August 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-34

**Comment by VanCardui** [comment]
Week 31 - 31st July to 6th August 2023

    https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-31

Details

Monday 31st July 2023

    Education Guild

Tuesday 1st  August 2023

    Governance Work group 
    Ambassador Work group 
    Ambassador Town Hall 
    Process Guild

Wednesday 5th July 2023

    Archives Workgroup 
    Process Modelling Workgroup
    Incubation Workgroup 
    Strategy Guild 

Thursday 6th July 2023

    Onboarding Workgroup 
    Treasury Guild
    AI Sandbox 
    DeepFunding Town Hall 

Friday 7th July 2023

    Video Workgroup 
    Writers Workgroup

**Comment by VanCardui** [comment]
### Week 34 - 21st August to 27th August 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-34

<details><summary>Details</summary>
<p>

### Monday 21st August 2023

- [ ] Education Guild 

### Tuesday 22nd August 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 23rd August 2023

- [ ] Archives Workgroup 
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 24th August 2023

- [ ] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 25th August 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
### Week 35 - 28th August to 3rd September 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/august-2023/week-35

<details><summary>Details</summary>
<p>

### Monday 28th August 2023

- [ ] Education Guild 

### Tuesday 29th August 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 30th August 2023

- [ ] Archives Workgroup 
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 31st August 2023

- [ ] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 1st September 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by stephen-rowan** [comment]
Some delays - because of bounty discussions

**Comment by stephen-rowan** [comment]
Data loss will impact August 2023 updates
Will impact cost budget for this item

**Comment by VanCardui** [comment]
Thanks to the fact that several people keep their meeting notes in a doc and don't delete it, we have lost much less than we might have done as a result of the Discord being hacked. 

This month some groups came to an end (e.g. Process Guild), and some were added, or made changes to their times or frequency (e.g. Incubation Workgroup became Incubation Guild).

Some meetings do noit give summaries - for example, DeepFunding Town Hall. Perhaps we should no longer include it.
