### ISSUE TITLE
Tool Development - August 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#51]
Created openAI account

Next steps - Initial setup of new version of archive-oracle

2023-08-11 Added generate-embeddings function 
https://github.com/SingularityNET-Archive/archive-oracle/commit/bedc29086b7fdf2571fef66f2ba2d034ba0ae79e
2023-08-12 Fetching gitHub files and some embedding updates
https://github.com/SingularityNET-Archive/archive-oracle/commit/9aa83ab4672981a88df48b810a0a84c972f443bd
2023-08-14 Fetch github and update database via api route
https://github.com/SingularityNET-Archive/archive-oracle/commit/819243f8af0a782692c2ec3f2ff3cbcf5a20ec3a
2023-08-15 Added Markdown parsing
https://github.com/SingularityNET-Archive/archive-oracle/commit/4500a3c99253ac02ffa40dea0d6aac4c4b3ac893
2023-08-26 Added new pages
https://github.com/SingularityNET-Archive/archive-oracle/commit/67734aac911628b74b2ab4f99af75a22bcbdbffe
2023-08-27 Added code to commit to GitHub
https://github.com/SingularityNET-Archive/archive-oracle/commit/5e362cecc9d68344b195d77b11f949105f8e3a16

**Comment by VanCardui** [comment]
## 23rd Aug
Andre has made great progress with this - see above

The current structure of the Archive is working well (date= heading 1, name of WG = heading 2, and any headings in the actual summary = heading 3)

But a question about Feb 2023 - archive-oracle didn't seem to be able to find stuff from that month - Andre to have a look to try and work out why

**Comment by stephen-rowan** [comment]
- [ ] Send final version of meeting summary templates to Andre - Vani

**Comment by stephen-rowan** [comment]
## 6th September 2023

2023-08-27 Added code to commit to GitHub
https://github.com/SingularityNET-Archive/archive-oracle/commit/5e362cecc9d68344b195d77b11f949105f8e3a16
