### ISSUE TITLE
Archive Gitbook - September 2023

### ISSUE THREAD

**Issue by stephen-rowan** [SingularityNET-Archive/SingularityNET-Archive#58]
## Month
-
- [x] Month Issue embedded in GitBook

## Notes

```
To insert detail use /detail slash command
``` 

## Week Numbers
- https://www.epochconverter.com/weeks/2023

### Week 36 - 4th September to 10th September 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-36
### Week 37 -11th September to 17th September 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-37
### Week 38 - 18th September to 24th September 2023 
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-38
### Week 39 - 25th September to 1st October 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-39

**Comment by VanCardui** [comment]
### Week 36 - 4th Sept to 10th Sept 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-36

<details><summary>Details</summary>
<p>

### Monday 4th September 2023

- [ ] Education Guild 

### Tuesday 5th September 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 6th September 2023

- [x ] Archives Workgroup - not this week
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 7th September 2023

- [x] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 8th September 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
### Week 37 - 11th Sept to 17th Sept 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-37

<details><summary>Details</summary>
<p>

### Monday 11th September 2023

- [ ] Education Guild 

### Tuesday 12th September 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 13th September 2023

- [ ] Archives Workgroup - not this week
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 14th September 2023

- [ ] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 15th September 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
### Week 38 - 18th Sept to 24th Sept 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-38

<details><summary>Details</summary>
<p>

### Monday 18th September 2023

- [ ] Education Guild 

### Tuesday 19th September 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 20th September 2023

- [ ] Archives Workgroup - not this week
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 21st September 2023

- [ ] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 22nd September 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
### Week 39 - 25th Sept to 1st Oct 2023
- https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2023/september-2023/week-39

<details><summary>Details</summary>
<p>

### Monday 25th September 2023

- [ ] Education Guild 

### Tuesday 26th September 2023

- [ ] Governance Work group
- [ ] Ambassador Work group
- [ ] Ambassador Town Hall 
- [ ] Process Guild

### Wednesday 27th September 2023

- [ ] Archives Workgroup - not this week
- [ ] Process Modelling Workgroup
- [ ] Incubation Workgroup
- [ ] Strategy Guild 

### Thursday 28th September 2023

- [ ] Onboarding Workgroup 
- [ ] Treasury Guild
- [ ] AI Sandbox
- [ ] DeepFunding Town Hall 


### Friday 29th September 2023

- [ ] Video Workgroup 
- [ ] Writers Workgroup


</p>
</details>

**Comment by VanCardui** [comment]
###To chase, as of 27th Sept:

##Week 36
- [ ] Education
- [ ] Ambassador assembly
- [ ] Ambassador TH
- [ ] Incubation 6th Sept
- [ ] Deepfunding TH
- [ ] Video
- [ ] Writers

##Week 37
- [ ] Ambassador assembly
- [ ] Ambassador TH
- [ ] deepfunding TH
- [ ] Video
- [ ] Writers

##Week 38
- [ ] Strategy Guild 20th Sept
- [ ] Video
- [ ] Writers
- [ ] Deepfunding TH
- [ ] Ambassador Assembly

Week 39
TBC

###Note
The meetings we consistently get no summaries for are:

- Ambassador Assembly - do Ambassadors prefer it not to be archived?
- Deepfunding TH - who's meant to do this? If nobody has ever been approached, then we need to - or, we need to just add a link to the video
- Video WG - need to find out if they prefer not to be archived, and - is this OK? or is it considered part of a WG's work?
- Writers - as above

**Comment by stephen-rowan** [comment]
Writers WG summary is a bounty and posted in the Writers WG channel - Kenichi
Timing issues associated with meeting summary bounties - Vani

**Comment by stephen-rowan** [comment]
- [ ] Action Item - talk to Deep Funding focus group and DF team about bounties for archiving and/or timestamping - @VanCardui 
- Deep Funding has its own dework board - so potential infrastructure is in place
