### ISSUE TITLE
Tool Development - October 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#65]
Next steps

Finish templates on UI
Make templates more readable on UI and connect to database

07.10.23 added more inputs and supabase function
https://github.com/SingularityNET-Archive/archive-oracle/commit/8a20596106b8418649766bb03478128c95e52542
09.10.23 connected database to form input and display
https://github.com/SingularityNET-Archive/archive-oracle/commit/d0656c53bd0a63946e69ec396a12a0a0a12c50a5
10.10.23 Fixed submit bug and added "other" tag
https://github.com/SingularityNET-Archive/archive-oracle/commit/bd44be76373372e0416580ba9e7d7f8d58f472b5
13.10.23 Added user constraint to database and date checking. 
https://github.com/SingularityNET-Archive/archive-oracle/commit/7bdec0502680b8e88fadf325d40b716ff27c2ece
16.10.23 Started prepping Summary confirmation page and added SignIn requirement
https://github.com/SingularityNET-Archive/archive-oracle/commit/5d2d7bb33cd71bd2aeb0059d8906a697b421eb5a
https://github.com/SingularityNET-Archive/archive-oracle/commit/8a6e39e0942536b16128ab6a17469db5e1be03a8
17.10.23 Fixed date and admin bug
https://github.com/SingularityNET-Archive/archive-oracle/commit/80f7302de6708fd6e5ea5ee7ac55c3e273e051f6
https://github.com/SingularityNET-Archive/archive-oracle/commit/a7c499094f893951f291ad2b79710982007c4468
18.10.23 Added name selection component, Fixed submit bug and added assignee select
https://github.com/SingularityNET-Archive/archive-oracle/commit/a71cb4a3f778e0925ff11d43019fecf1664ce89e
https://github.com/SingularityNET-Archive/archive-oracle/commit/e0d5ef3567c194436728228af1cd4a067352baad
19.10.23 Updated Role checking
https://github.com/SingularityNET-Archive/archive-oracle/commit/825d0f2bf85cf4819b0e6afaa703c4a388b09cb6
20.10.23 Implemented easy template customization
https://github.com/SingularityNET-Archive/archive-oracle/commit/a691ba37036dc20481e2de150c0ffba9b28dc6e8
22.10.23 Cleaned up code and updated mininav styling
https://github.com/SingularityNET-Archive/archive-oracle/commit/070024581c57986b2ed5057b88326303211bd65f

**Comment by stephen-rowan** [comment]
Potential to capture WG decisions - lends itself to transparency and accountability - Felix
When running can be used to train LLM - Vani
Compare and contrast different decision making in WGs - Vani
Build decision trees and context - Felix

**Comment by stephen-rowan** [comment]
- Add status to Action items
- TO DO / IN PROGRESS / DONE / BLOCKED / CANCELLED

**Comment by stephen-rowan** [comment]
We may have to data clean duplicate names in name select.
