### ISSUE TITLE
Tool Development - November 2023

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#70]
Make templates more readable
Finish "Confirm Summaries" page
Add Discord and GitBook integration
Test all features with different roles
Finalize and get ready to present to community

04.11.23 Styling and dropdowns
https://github.com/SingularityNET-Archive/archive-oracle/commit/25a64f46c05a85000b4be4c85f839383bc8e235c
05.11.23 Added dynamic tags
https://github.com/SingularityNET-Archive/archive-oracle/commit/d3fe231bf3eb70abddde8cb52b22bc60fae11050
07.11.23 Added markdown generation, GitBook commit and skeleton for Discord msg
https://github.com/SingularityNET-Archive/archive-oracle/commit/ac15088ec6e4517eb564f6c67ec77d00a49fbd17
08.11.23 Added Guards for multiple commits, finalised format of Discord message, added meeting select options and finalised tool for testing
https://github.com/SingularityNET-Archive/archive-oracle/commit/2b09c79523a55701e0a14e48002f33b37ff7af3a
https://github.com/SingularityNET-Archive/archive-oracle/commit/f7439c6938edfbb91c438c4ae6a24c6ce0242975
https://github.com/SingularityNET-Archive/archive-oracle/commit/fca3fdcd6877673bbf0daba83bd3f7f6add6ef09
09.11.23 Updated Discord format to take more characters and fixed bugs
https://github.com/SingularityNET-Archive/archive-oracle/commit/f2d4aa225e9a993e88a23fecdbd4fce6c0768e3d
https://github.com/SingularityNET-Archive/archive-oracle/commit/5b097c56bc3ff5740ad7d9cba3a8391d67193b61
10.11.23 Turned Template Items into generic functions
https://github.com/SingularityNET-Archive/archive-oracle/commit/93688f7adc0488d0f4f94ba0cbf9dffaab50d987
12.11.23 Finalized for testing - made core changes to accomodate for customization and added new items
https://github.com/SingularityNET-Archive/archive-oracle/commit/0975935cd8f453b9607555c46c9c70591b84ebc3
https://github.com/SingularityNET-Archive/archive-oracle/commit/4d36573d2ea14201c6bcea9dc94c64580cf97028
13.11.23 Finalized updates for testing
https://github.com/SingularityNET-Archive/archive-oracle/commit/b64e6e73386a1cc62a990c766dbfd3971d372674
22.11.23 Added new saving features and dropdown for meeting type
https://github.com/SingularityNET-Archive/archive-oracle/commit/11e0dcbe35e226d6ac22f92aa4a3cff64657b6b6

List of all repo commits for November
https://github.com/SingularityNET-Archive/archive-oracle/commits/main/?since=2023-11-01&until=2023-11-30

**Comment by stephen-rowan** [comment]
Andre to meet with Vani on Template design and use.
