### ISSUE TITLE
Tool Development - January 2024

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#79]
January 2024 tool updates

All January commits
https://github.com/SingularityNET-Archive/archive-oracle/commits/main/?since=2024-01-01&until=2024-01-31

**Comment by stephen-rowan** [comment]
## Issue Template - created by Andre and reviewed at meeting

- Add [Other] to list
- Add dropdown for workgroups
- Andre to catch up issues to close

Issue triage once a week where issues are sorted into status

**Comment by Andre-Diamond** [comment]
I updated the issue template and caught up and closed all testing issues.
Next step is to look at leftover issues and any new issues that comes up
