### ISSUE TITLE
Setup of LLM and Archive Search tooling - Ubio

### ISSUE THREAD

**Issue by VanCardui** [SingularityNET-Archive/SingularityNET-Archive#96]
this connects with our old Issue on this topic: https://github.com/SingularityNET-Archive/SingularityNET-Archive/issues/29

Ubio Obu is interested in working on this - we've sent him a brief https://docs.google.com/document/d/1LROsgVAQ9fQbNgMRK5qMI8q8KYsN-rGI-Gq9lvXAN5w/edit?usp=sharing

This issue should probably be closed when we hear back from him and the brief is agreed - then it should probably become monthly issues called something like  "**_AI tooling - Ubio: Feb_**" or similar

**Comment by Andre-Diamond** [comment]
I'll send the new document that explains the AI features we need to Ubio and also mention the monthly rewards we agreed on
