### ISSUE TITLE
Tool Development - February 2024

### ISSUE THREAD

**Issue by Andre-Diamond** [SingularityNET-Archive/SingularityNET-Archive#98]
Fixing of issues and adding new features to Summary tool

All February 2024 commits

Main Branch
https://github.com/SingularityNET-Archive/archive-oracle/commits/main/?since=2024-02-01&until=2024-02-29

Development branch
https://github.com/SingularityNET-Archive/archive-oracle/commits/development?since=2024-02-01&until=2024-02-29

**Comment by stephen-rowan** [comment]
Andre started working on Town Hall Template to add embedded YouTube video link and associated timestamps

**Comment by Andre-Diamond** [comment]
I'll also work on the feature to add meetings that did not receive summaries

**Comment by Andre-Diamond** [comment]
Created a status of summaries page.
Fixed bugs found from community created issues.
Added Town Hall templates to tool.
Added template for one-off events
Added automation to remove resolved Agenda items and "done" action items after we archived the summaries.
So the next summary will be auto-filled without these agenda and action items.

**Comment by Andre-Diamond** [comment]
Added "No summary Given" button
Added contact info for furhter assistance
Added Discussion Points to Gamers Guild template

**Comment by stephen-rowan** [comment]
Option for meeting cancelled to be added ? - Vani
